apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer # Выбор подов, принадлежащих вашему приложению consumer
  ports:
    - protocol: TCP
      port: 8082 # Порт, на котором работает ваше приложение producer в контейнере
      targetPort: 8082 # Порт вашего приложения producer в контейнере
